apiVersion: batch/v1
kind: Job
metadata:
  name: import-genes-job
spec:
  template:
    spec:
      containers:
      - name: genes-importer
        image: gcr.io/devenv-215523/genes-importer:${IMPORTER_VERSION}
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - |
            sleep 2s
            trap "touch /tmp/pod/terminated" EXIT
            java -Xms256M -Xmx1G -jar /app/genes-importer.jar
        resources:
          requests:
            memory: "512M"
          limits:
            memory: "1G"
        env:
          - name: JVM_OPTS
            value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
          - name: GFF3_FTP_URLS
            value:  GRCh38_29;ftp://anonymous@ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.annotation.gff3.gz|GRCh38_30;ftp://anonymous@ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_30/gencode.v30.annotation.gff3.gz|GRCh38_24;ftp://anonymous@ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_24/gencode.v24.annotation.gff3.gz|hg19_29;ftp://anonymous@ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/GRCh37_mapping/gencode.v29lift37.annotation.gff3.gz|hg19_19;ftp://anonymous@ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.annotation.gff3.gz|mm10_21;ftp://anonymous@ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M21/gencode.vM21.annotation.gff3.gz|mm10_20;ftp://anonymous@ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M20/gencode.vM20.annotation.gff3.gz|mm10_4;ftp://anonymous@ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M4/gencode.vM4.annotation.gff3.gz|GRCh38_40;ftp://anonymous@ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_40/gencode.v40.basic.annotation.gff3.gz|mm10_25;ftp://anonymous@ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.basic.annotation.gff3.gz
          - name: DB_SCHEMA
            value: "${DB_SCHEMA}"
          - name: DB_URL
            value: "jdbc:postgresql://127.0.0.1:5432/genes-db"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: genes-db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: genes-db-credentials
                key: password
        volumeMounts:
          - name: tmp-pod
            mountPath: /tmp/pod
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/bin/sh", "-c"]
        args:
          - |
            /cloud_sql_proxy -instances=devenv-215523:us-east1:genes-instance=tcp:5432 -credential_file=/secrets/cloudsql/staging-service-account.json & CHILD_PID=$!
            (while true; do if [[ -f "/tmp/pod/terminated" ]]; then kill $CHILD_PID; echo "Killed $CHILD_PID because the main container terminated."; fi; sleep 1; done) &
            wait $CHILD_PID
            if [[ -f "/tmp/pod/terminated" ]]; then exit 0; echo "Job completed. Exiting..."; fi
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: service-account-key
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: tmp-pod
            mountPath: /tmp/pod
            readOnly: true
      volumes:
        - name: service-account-key
          secret:
            secretName: service-account-key
        - name: tmp-pod
          emptyDir: {}
      restartPolicy: Never