name: Build and Push Importer

on:
  create:
    tags:
      - v*

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  IMPORTER_IMAGE: peaks-importer
  REGISTRY_HOSTNAME: gcr.io

jobs:

  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v2
        
      - name: Test importer
        run: |
          importer/scripts/test.sh
  setup-build-publish-importer:
    name: Setup, Build, Publish Importer
    runs-on: ubuntu-latest
    needs: test
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build
      run: |        
        docker build -t image \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" importer

    # Push the image to GCP
    - name: Publish
      run: |
        docker tag image "$REGISTRY_HOSTNAME"/"$GKE_PROJECT"/"$IMPORTER_IMAGE":"${GITHUB_REF/refs\/tags\//}" && \
        docker push $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMPORTER_IMAGE:${GITHUB_REF/refs\/tags\//}
