apiVersion: apps/v1
kind: Deployment
metadata:
  name: snps-service-deployment
  labels:
    app: snps-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snps-service
  template:
    metadata:
      labels:
        app: snps-service
    spec:
      containers:
      - name: snps-service
        image: gcr.io/devenv-215523/snps-service:${SERVICE_VERSION}
        env:
          - name: POSTGRES_SCHEMA
            value: "${DB_SCHEMA}"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: genes-db-credentials
                key: username
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: genes-db-credentials
                key: password
          - name: POSTGRES_DB
            value: "genes-db"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=devenv-215523:us-east1:genes-instance=tcp:5432",
                  "-credential_file=/secrets/cloudsql/staging-service-account.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: service-account-key
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: service-account-key
          secret:
            secretName: service-account-key
---
apiVersion: v1
kind: Service
metadata:
  name: snps-service-service
  labels:
    app: snps-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: snps-service
---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: snps-api-cert
spec:
  domains:
    - snps.staging.wenglab.org
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: snps-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "staging-snps-external-ip"
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/managed-certificates: "snps-api-cert"
spec:
  backend:
    serviceName: snps-service-service
    servicePort: 80
