#!/bin/bash
GCR_PROJECT_ID=devenv-215523
SERVICE_DOCKER_IMAGE_NAME=factor-service
IMPORTER_DOCKER_IMAGE_NAME=factor-importer
KUBE_DEPLOYMENT_NAME=factor-service-deployment
KUBE_DEPLOYMENT_CONTAINER_NAME=factor-service